spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/smart-gear_api?createDatabaseIfNotExist=true
    username: root
    password: Terminal360
  jpa:
    show-sql: true